import SpaceStationImage from '../../Assets/SpaceStationFrontPage.png'
import AstronautCloseFrontPage from '../../Assets/AstronautCloseFrontPage.png'
import AstronautFrontPage from '../../Assets/AstronautFrontPage.png'
import PlanetFrontPage from '../../Assets/PlanetFrontPage.png'

export const articles = [
	{
		id: 1,
		title: 'La station spatiale',
		imageFront: SpaceStationImage,
		content: `
The International Space Station or International Space Station (ISS) is a facility in low Earth orbit permanently manned by an international crew dedicated to scientific research in the space environment. It is the largest man-made object placed in Earth orbit. It spans 110 m in length, 74 m in width and 30 m in height and has a mass of around 420 tonnes in 2019.
At the origin of this ambitious project, the President of the United States Ronald Reagan in 1983. Led by the United States Space Agency (NASA), the program has been developed jointly with the Russian Space Agency (ROSCOSMOS) since 1993 , also with the participation of the European (ESA), Japanese (JAXA) and Canadian (CSA) space agencies.
The assembly in orbit of the International Space Station (ISS) began in 1998. It was not finalized until thirteen years later, after around forty flights intended to transport the elements necessary for its construction.
`,
		image: '',
		photos: [],
		numbers: '',
	},
	{
		id: 2,
		title: 'Les austronautes',
		imageFront: AstronautCloseFrontPage,
		content: `The ISS crew is currently made up of ten members: NASA astronauts Raja Chari, Thomas Marshburn, Kayla Barron and Mark Vande Hei, German European Space Agency (ESA) astronaut Matthias Maurer and cosmonauts from Roscosmos Anton Shkaplerov (commander) and Pyotr Dubrov were joined by Oleg Artemiev, Denis Matveev and Sergei Korsakov.
Each of the astronauts during their stay, which lasts 3 to 6 months, shares their working time with different tasks: assembly/maintenance operations and scientific work mainly on biology, materials science and astronomy. To live in space is to live in weightlessness, a phenomenon experienced in the apparent absence of gravity. For the human body, this life without ups and downs leads to significant physiological changes.
Since its beginnings in 1998, it has welcomed more than 250 astronauts, including recently the Frenchman Thomas Pesquet.
`,
	},
	{
		id: 3,
		title: "L'univers",
		imageFront: PlanetFrontPage,
		content: `Orbiting in space around 400 km around the earth, the ISS rotates at nearly 8 km/s and thus circles the planet fifteen times a day. In one day, the station travels about the same distance as it would take to go from Earth to the Moon and back. The space station is very valuable for research because it allows men to have a foot in space. For millions of years, space remained out of human reach.
The Universe refers to everything that exists. Space is that expanse which separates us from the stars, and more generally separates the stars from each other. It is, from our point of view, Earthlings, beyond the part of our Earth atmosphere.
However, the limits of space cannot be precisely defined: the density of the atmosphere, the envelope of gas that surrounds and protects us, gradually decreases as we rise in altitude. Thus, 200 km above our heads, there remains a residual atmosphere.
`,
	},
	{
		id: 4,
		title: "L'univers",
		imageFront: AstronautFrontPage,
		content: `The Universe is the sum of all that exists: space, time and matter. The Universe is a scientific notion that designates all the matter (stars, planets, gas, dust) in space.
Time, space, energy and matter were born 13.8 billion years ago in an event called the Big Bang. In its very first moments, the Universe was infinitely dense, extremely hot, and contained nothing but energy. A tiny fraction of a second later, it was teeming with elementary particles, generated by its cooling. A few hundred thousand years later, these particles formed the first atoms.
The Big Bang was not an explosion but an expansion of space, in all directions. To date, we do not know exactly whether the Universe is finite (there would be an end and nothing after) or infinite (endless). It is very large, immensely large! The current observable size is estimated at 13.7 billion light-years.`,
	},
]
